SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `mst_affiliation` (`id`, `unique_name`, `sort_number`, `show_in_select_box`, `is_enabled`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
(1, '美浦', 1, 1, 1, NULL, NULL, NULL, NULL),
(2, '栗東', 2, 1, 1, NULL, NULL, NULL, NULL),
(3, '地方', 3, 1, 1, NULL, NULL, NULL, NULL),
(4, '海外', 4, 1, 1, NULL, NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
