SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


INSERT INTO `mst_race_category_sex` (`id`, `name`, `short_name_3`, `umm_category`, `sort_number`, `is_enabled`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
(1, '牡', '牡', NULL, NULL, 1, NULL, NULL, NULL, NULL),
(2, '牝', '牝', 'ティアラ', 2, 1, NULL, NULL, NULL, NULL),
(3, '牡・牝', '牡・牝', NULL, 3, 1, NULL, NULL, NULL, NULL),
(4, 'セン', 'セン', NULL, NULL, 0, NULL, NULL, NULL, NULL),
(5, '牡・セン', '牡・騙', NULL, NULL, 1, NULL, NULL, NULL, NULL),
(6, '牝・セン', '牝・騙', NULL, NULL, 0, NULL, NULL, NULL, NULL),
(7, '無制限', '', NULL, 1, 1, NULL, NULL, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
